apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: noteapp-git
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/VariableExp0rt/noteapp